services:
  postgres:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=postgrespw
    ports:
      - 5432:5432
    volumes:
        #Anonymous volume
      - /var/lib/postgresql/data
      #- pgdata:/var/lib/postgresql/data
  mongodb:
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=mongopw
    ports:
      - 27018:27017
    volumes:
        #Anonymous volume
      - /var/lib/mongodb/data
      #- mongodata:/var/lib/mongodb/data
#Disable for Anonymous volumes
#volumes:
#  pgdata:
#  mongodata:  